In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('glass.csv')

In [3]:
data

      Id       RI     Na    Mg    Al    Si      K    Ca    Ba   Fe  Type
0      1  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.0     1
1      2  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.0     1
2      3  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.0     1
3      4  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.0     1
4      5  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.0     1
..   ...      ...    ...   ...   ...    ...   ...   ...   ...  ...   ...
209  210  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.0     7
210  211  1.51685  14.92  0.00  1.99  73.06  0.00  8.40  1.59  0.0     7
211  212  1.52065  14.36  0.00  2.02  73.42  0.00  8.44  1.64  0.0     7
212  213  1.51651  14.38  0.00  1.94  73.61  0.00  8.48  1.57  0.0     7
213  214  1.51711  14.23  0.00  2.08  73.36  0.00  8.62  1.67  0.0     7

[214 rows x 11 columns]

In [4]:
from sklearn.svm import SVC
from sklearn import svm
import numpy as np

C:\Users\riyaj\anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [5]:
x = np.array([[3,4],[1,4],[2,3],[6,-1],[7,-1],[5,-3]])
y = np.array([-1,-1,-1,1,1,1])

In [7]:
l = SVC(C=1e5, kernel="linear")
l.fit(x,y)

SVC(C=100000.0, kernel='linear')

In [9]:
print("w= ",l.coef_)
print("b= ",l.intercept_)
print("Indices of support vectors= ",l.support_)
print("Support vectors = ",l.support_vectors_)
print("No. of support vectors from each class = ",l.n_support_)
print("Coefficient of support vectors in decision function = ",np.abs(l.dual_coef_))

w=  [[ 0.25 -0.25]]
b=  [-0.75]
Indices of support vectors=  [2 3]
Support vectors =  [[ 2.  3.]
 [ 6. -1.]]
No. of support vectors from each class =  [1 1]
Coefficient of support vectors in decision function =  [[0.0625 0.0625]]

In [10]:
data.head()

   Id       RI     Na    Mg    Al    Si      K    Ca   Ba   Fe  Type
0   1  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1   2  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2   3  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3   4  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4   5  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

In [14]:
x = data.drop("Type",axis=1)
y = data.Type

In [15]:
x

      Id       RI     Na    Mg    Al    Si      K    Ca    Ba   Fe
0      1  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.0
1      2  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.0
2      3  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.0
3      4  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.0
4      5  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.0
..   ...      ...    ...   ...   ...    ...   ...   ...   ...  ...
209  210  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.0
210  211  1.51685  14.92  0.00  1.99  73.06  0.00  8.40  1.59  0.0
211  212  1.52065  14.36  0.00  2.02  73.42  0.00  8.44  1.64  0.0
212  213  1.51651  14.38  0.00  1.94  73.61  0.00  8.48  1.57  0.0
213  214  1.51711  14.23  0.00  2.08  73.36  0.00  8.62  1.67  0.0

[214 rows x 10 columns]

In [16]:
y

0      1
1      1
2      1
3      1
4      1
      ..
209    7
210    7
211    7
212    7
213    7
Name: Type, Length: 214, dtype: int64

In [17]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3)

In [18]:
linear = svm.SVC(kernel="linear")

In [19]:
linear.fit(x_train,y_train)

SVC(kernel='linear')

In [21]:
print(linear.support_vectors_)
print(linear.n_support_)

[[7.00000e+01 1.52300e+00 1.33100e+01 3.58000e+00 8.20000e-01 7.19900e+01
  1.20000e-01 1.01700e+01 0.00000e+00 3.00000e-02]
 [7.20000e+01 1.51848e+00 1.36400e+01 3.87000e+00 1.27000e+00 7.19600e+01
  5.40000e-01 8.32000e+00 0.00000e+00 3.20000e-01]
 [1.46000e+02 1.51839e+00 1.28500e+01 3.67000e+00 1.24000e+00 7.25700e+01
  6.20000e-01 8.68000e+00 0.00000e+00 3.50000e-01]
 [1.47000e+02 1.51769e+00 1.36500e+01 3.66000e+00 1.11000e+00 7.27700e+01
  1.10000e-01 8.60000e+00 0.00000e+00 0.00000e+00]
 [1.63000e+02 1.52211e+00 1.41900e+01 3.78000e+00 9.10000e-01 7.13600e+01
  2.30000e-01 9.14000e+00 0.00000e+00 3.70000e-01]
 [1.73000e+02 1.51321e+00 1.30000e+01 0.00000e+00 3.02000e+00 7.07000e+01
  6.21000e+00 6.93000e+00 0.00000e+00 0.00000e+00]
 [1.65000e+02 1.51915e+00 1.27300e+01 1.85000e+00 1.86000e+00 7.26900e+01
  6.00000e-01 1.00900e+01 0.00000e+00 0.00000e+00]
 [1.64000e+02 1.51514e+00 1.40100e+01 2.68000e+00 3.50000e+00 6.98900e+01
  1.68000e+00 5.87000e+00 2.20000e+00 0.00000e+00]
 [1.74000e+02 1.52043e+00 1.33800e+01 0.00000e+00 1.40000e+00 7.22500e+01
  3.30000e-01 1.25000e+01 0.00000e+00 0.00000e+00]
 [1.78000e+02 1.51937e+00 1.37900e+01 2.41000e+00 1.19000e+00 7.27600e+01
  0.00000e+00 9.77000e+00 0.00000e+00 0.00000e+00]
 [1.83000e+02 1.51916e+00 1.41500e+01 0.00000e+00 2.09000e+00 7.27400e+01
  0.00000e+00 1.08800e+01 0.00000e+00 0.00000e+00]
 [1.85000e+02 1.51115e+00 1.73800e+01 0.00000e+00 3.40000e-01 7.54100e+01
  0.00000e+00 6.65000e+00 0.00000e+00 0.00000e+00]
 [1.89000e+02 1.52247e+00 1.48600e+01 2.20000e+00 2.06000e+00 7.02600e+01
  7.60000e-01 9.76000e+00 0.00000e+00 0.00000e+00]
 [1.92000e+02 1.51602e+00 1.48500e+01 0.00000e+00 2.38000e+00 7.32800e+01
  0.00000e+00 8.76000e+00 6.40000e-01 9.00000e-02]
 [1.86000e+02 1.51131e+00 1.36900e+01 3.20000e+00 1.81000e+00 7.28100e+01
  1.76000e+00 5.43000e+00 1.19000e+00 0.00000e+00]]
[1 2 2 4 3 3]

In [22]:
y_pred = linear.predict(x_test)

In [23]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred))
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

1.0
[[19  0  0  0  0  0]
 [ 0 26  0  0  0  0]
 [ 0  0  8  0  0  0]
 [ 0  0  0  3  0  0]
 [ 0  0  0  0  1  0]
 [ 0  0  0  0  0  8]]
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        19
           2       1.00      1.00      1.00        26
           3       1.00      1.00      1.00         8
           5       1.00      1.00      1.00         3
           6       1.00      1.00      1.00         1
           7       1.00      1.00      1.00         8

    accuracy                           1.00        65
   macro avg       1.00      1.00      1.00        65
weighted avg       1.00      1.00      1.00        65

In [24]:
model1 = SVC(kernel = "sigmoid")
model2 = SVC(kernel = "poly")
model3 = SVC(kernel = "rbf")
model1.fit(x_train,y_train)
model2.fit(x_train,y_train)
model3.fit(x_train,y_train)

SVC()

In [25]:
y_pred1 = model1.predict(x_test)
y_pred2 = model2.predict(x_test)
y_pred3 = model3.predict(x_test)

In [26]:
print("Accuracy score of model1 = ",accuracy_score(y_test,y_pred))
print("Accuracy score of model2 = ",accuracy_score(y_test,y_pred))
print("Accuracy score of model3 = ",accuracy_score(y_test,y_pred))

Accuracy score of model1 =  1.0
Accuracy score of model2 =  1.0
Accuracy score of model3 =  1.0

In [27]:
print("Confusion matrix of model 1 = ",confusion_matrix(y_test, y_pred))
print("Confusion matrix of model 2 = ",confusion_matrix(y_test, y_pred))
print("Confusion matrix of model 3 = ",confusion_matrix(y_test, y_pred))

Confusion matrix of model 1 =  [[19  0  0  0  0  0]
 [ 0 26  0  0  0  0]
 [ 0  0  8  0  0  0]
 [ 0  0  0  3  0  0]
 [ 0  0  0  0  1  0]
 [ 0  0  0  0  0  8]]
Confusion matrix of model 2 =  [[19  0  0  0  0  0]
 [ 0 26  0  0  0  0]
 [ 0  0  8  0  0  0]
 [ 0  0  0  3  0  0]
 [ 0  0  0  0  1  0]
 [ 0  0  0  0  0  8]]
Confusion matrix of model 3 =  [[19  0  0  0  0  0]
 [ 0 26  0  0  0  0]
 [ 0  0  8  0  0  0]
 [ 0  0  0  3  0  0]
 [ 0  0  0  0  1  0]
 [ 0  0  0  0  0  8]]

In [28]:
print("Classification report of model 1: ",classification_report(y_test, y_pred))
print("Classification report of model 2: ",classification_report(y_test, y_pred))
print("Classification report of model 3: ",classification_report(y_test, y_pred))

Classification report of model 1:                precision    recall  f1-score   support

           1       1.00      1.00      1.00        19
           2       1.00      1.00      1.00        26
           3       1.00      1.00      1.00         8
           5       1.00      1.00      1.00         3
           6       1.00      1.00      1.00         1
           7       1.00      1.00      1.00         8

    accuracy                           1.00        65
   macro avg       1.00      1.00      1.00        65
weighted avg       1.00      1.00      1.00        65

Classification report of model 2:                precision    recall  f1-score   support

           1       1.00      1.00      1.00        19
           2       1.00      1.00      1.00        26
           3       1.00      1.00      1.00         8
           5       1.00      1.00      1.00         3
           6       1.00      1.00      1.00         1
           7       1.00      1.00      1.00         8

    accuracy                           1.00        65
   macro avg       1.00      1.00      1.00        65
weighted avg       1.00      1.00      1.00        65

Classification report of model 3:                precision    recall  f1-score   support

           1       1.00      1.00      1.00        19
           2       1.00      1.00      1.00        26
           3       1.00      1.00      1.00         8
           5       1.00      1.00      1.00         3
           6       1.00      1.00      1.00         1
           7       1.00      1.00      1.00         8

    accuracy                           1.00        65
   macro avg       1.00      1.00      1.00        65
weighted avg       1.00      1.00      1.00        65